.TH "dpl_group_internal_t" 3 "8 Apr 2008" "Version Version 1.0" "libdpl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dpl_group_internal_t \- DPL group cache structure. Intended for internal use.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <dpl_types.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBgrp_size\fP"
.br
.RI "\fISize of group. \fP"
.ti -1c
.RI "int \fBgrp_nodes\fP"
.br
.RI "\fINumber of nodes in the group. \fP"
.ti -1c
.RI "int * \fBgrp_node_ranks\fP"
.br
.RI "\fIArray of ranks of nodes in the group. \fP"
.ti -1c
.RI "int \fBgrp_pseudoroots\fP"
.br
.RI "\fINumber of pseudoroots in the group. \fP"
.ti -1c
.RI "int * \fBgrp_pseudoroot_ranks\fP"
.br
.RI "\fIArray of ranks of pseudoroots in the group. \fP"
.ti -1c
.RI "int \fBgrp_roots\fP"
.br
.RI "\fINumber of roots in the group. \fP"
.ti -1c
.RI "int * \fBgrp_root_ranks\fP"
.br
.RI "\fIArray of ranks of roots in the group. \fP"
.ti -1c
.RI "int \fBgrp_number\fP"
.br
.RI "\fIGroup number. \fP"
.in -1c
.SH "Detailed Description"
.PP 
DPL group cache structure. Intended for internal use. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libdpl from the source code.
